$nrconf{verbosity} = 0;
$nrconf{restart} = 'l';
$nrconf{sendnotify} = 0;
$nrconf{has_pam_systemd} = 0;
$nrconf{interpscan} = 1;
$nrconf{perlcache} = undef;
$nrconf{blacklist} = [];
$nrconf{blacklist_interp} = [];
$nrconf{blacklist_rc} = [];
$nrconf{kernelhints} = 0;
$nrconf{ucodehints} = 0;
1;
